
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.8'
version_full = '790a6f3a5d2edeafcd1de8b4d2d32b861ef24a36'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
