
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.3.7'
version_full = 'e7945706608f5a75fe7baf9a3cb268ddb49773bc'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
